-- ============================================
-- 添加 subtitle_rewritten 字段到 media_tasks 表
-- ============================================
-- 
-- 用途：为 AI 改写功能添加数据库字段支持
-- 执行方式：在 Supabase SQL Editor 中直接运行此脚本
-- 
-- 注意：此脚本使用 IF NOT EXISTS，可以安全地重复执行
-- ============================================

-- 添加 subtitle_rewritten 字段（AI 改写后的文案）
ALTER TABLE "media_tasks" 
ADD COLUMN IF NOT EXISTS "subtitle_rewritten" TEXT;

-- 验证字段是否添加成功
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'media_tasks' 
        AND column_name = 'subtitle_rewritten'
    ) THEN
        RAISE NOTICE '✅ subtitle_rewritten 字段已成功添加';
    ELSE
        RAISE EXCEPTION '❌ subtitle_rewritten 字段添加失败';
    END IF;
END $$;

-- 可选：为已有数据添加注释
COMMENT ON COLUMN "media_tasks"."subtitle_rewritten" IS 'AI rewritten content for viral scripts (generated by Gemini)';
